#! /usr/local/bin/bash

sql() {
    mycli -u root --pass testtest -h dev.cluster-crzjfb0ik55e.us-east-1.rds.amazonaws.com -D govworks -e "$1"
}

api_call() {
    #Parameter 1 is URL
    #parameter 2 is Payload
    curl $1 \
    -H 'Accept: application/json, text/plain, */*' \
    -H 'Referer: https://dev.passportcenter.com/checkout/step4' \
    -H 'Origin: https://dev.passportcenter.com' \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' \
    -H 'Content-Type: application/json;charset=UTF-8' \
    --request POST \
    --data-binary $"$2" --compressed
}