#! /usr/local/bin/bash

# product option email source
email="$([ $3 ] && echo $3 || echo "$(random_email)")"
run core/createlead $1 $2 $email $4

UUID=$(get_lead_uuid "$email" | sed -E "s/\"//g" | sed -E "s/uuid//g" | sed -E "/^$/d");
api_call "https://api.dev.govworks.com/api/trial/$UUID" '' "GET" #Hit this endpoint to start the trial

set_user_password_to_password $email;

echo "Create Trial: Trial Created, Login with: $email"