#! /usr/local/bin/bash
source ./util
#                         product option email source
/usr/local/bin/bash ./createlead $1 $2 $3 $4

email=$3
UUID=$(get_lead_uuid "$email" | sed -E "s/\"//g" | sed -E "s/uuid//g" | sed -E "/^$/d");
curl -L --write-out "$email $UUID %{http_code}\n" --silent --output /dev/null "https://api.dev.govworks.com/api/trial/$UUID"

set_user_password_to_password $email;

echo "Login with $email";