#! /usr/local/bin/bash

# Parameters: email

get_application_fill_model() {
    #The argument is the product type. Ex. passport-renewal
    set_name
    PERSONAL_PROFILE=`envsubst <$ROOT_DIRECTORY/data/application-models/personal-profile.json`;
    APPLICATION_DATA=`envsubst <$ROOT_DIRECTORY/data/application-models/$1.json`;

    MODEL="{\"model\": {"$PERSONAL_PROFILE","$APPLICATION_DATA"}}"

    echo $MODEL;
}

get_user_order_product_type() {
    # Argument 1 is user's email
    GET_PRODUCT_TYPE_QUERY="SELECT products.subtype FROM users JOIN user_orders ON users.id = user_orders.user_id  JOIN orders ON orders.id = user_orders.order_id JOIN travelers ON travelers.order_id = orders.id JOIN applications ON applications.traveler_id = travelers.id JOIN products ON products.id = applications.product_id WHERE users.email = '$1' LIMIT 1"
    RESULT="$(sql "$GET_PRODUCT_TYPE_QUERY")"
    remove_first_line_from_sql_output "$RESULT"
}

GET_TRAVELER_QUERY="SELECT travelers.uuid FROM users JOIN user_orders ON users.id = user_orders.user_id JOIN travelers ON travelers.order_id = user_orders.order_id WHERE users.email = '$1' LIMIT 1 "
TRAVELER_UUID=$( sql "$GET_TRAVELER_QUERY" | sed -n '1!p' | sed -E "s/\"//g")

URL="$API_URL/traveler/$TRAVELER_UUID/update/model"

# GET LOGIN COOKIE
login $1

# POST FILLED APPLICATION FOR TRAVELER

if [[ -z "$2" ]] #If the second parameter is empty, auto detect the product type of the application
then
    PRODUCT_TYPE="$(get_user_order_product_type "$1")"
    echo "Fill App: Detected $PRODUCT_TYPE application"
else
    PRODUCT_TYPE="$2"
    echo "Fill App: Filling application as $2"
fi

api_call "$URL" "$(get_application_fill_model "$PRODUCT_TYPE")"
echo
echo "Fill App: Filled application for $1"