#! /usr/local/bin/bash

escape='\033'
reset="${escape}[0m"

# Color codes
red="${escape}[0;31m"
green="${escape}[0;32m"
blue="${escape}[0;34m"
purple="${escape}[0;35m"
yellow="${escape}[1;33m"
cyan="${escape}[0;36m"

red() {
    echo -e "${red}$1${reset}"
}

green() {
    echo -e "${green}$1${reset}"
}

blue() {
    echo -e "${blue}$1${reset}"
}

purple() {
    echo -e "${purple}$1${reset}"
}

yellow() {
    echo -e "${yellow}$1${reset}"
}

cyan() {
    echo -e "${cyan}$1${reset}"
}