#! /usr/local/bin/bash

reset="${escape}[0m"

# Color codes
red=$(tput setaf 1)
green=$(tput setaf 2)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
yellow=$(tput setaf 3)
cyan=$(tput setaf 6)

red() {
    echo -e "${red}$1${reset}"
}

green() {
    echo -e "${green}$1${reset}"
}

blue() {
    echo -e "${blue}$1${reset}"
}

purple() {
    echo -e "${purple}$1${reset}"
}

yellow() {
    echo -e "${yellow}$1${reset}"
}

cyan() {
    echo -e "${cyan}$1${reset}"
}