#! /usr/local/bin/bash

get_lead_uuid() {
    QUERY="SELECT uuid from hot_leads WHERE email = '$1'"
    sql "$QUERY";
}

get_name() {
    # Argument 1 user's email
    GET_NAME_QUERY="SELECT first_name, last_name FROM users WHERE email = '$1'"
    RESULT="$(sql "$GET_NAME_QUERY")"
    FULLNAME=$(remove_first_line_from_sql_output "$RESULT")
    export FIRSTNAME=$(cut -f1 <<< $FULLNAME )
    export LASTNAME=$(cut -f2 <<< $FULLNAME )
}

# Magic https://stackoverflow.com/a/449890
set_name() {
    FULLNAME=$(head -$((${RANDOM} % `wc -l < ./data/names.txt` + 1)) ./data/names.txt | tail -1)
    export FIRSTNAME=$(cut -d',' -f1 <<< $FULLNAME )
    export LASTNAME=$(cut -d',' -f2 <<< $FULLNAME )
    export MIDDLENAME=$(cut -d',' -f3 <<< $FULLNAME )
}

set_user_password_to_password() {
    CHANGE_PASSWORD_QUERY="UPDATE users SET password = '\$2y\$10\$2/Es3Q5ec7g5TlgcMuJD4O22ylxHSO3K06F1qcx5XKfYgCY6Df7y6', new = 0 WHERE email = '$1'"
    sql "$CHANGE_PASSWORD_QUERY"
}

run() {
    eval "/usr/local/bin/bash $ROOT_DIRECTORY/$@"
}

# @description Returns the given value if there is one, if not, returns the second argument as the default string
# @example tern "$myvar" "Default Value"
tern() {
   [[ -n "$1" ]] && echo "$1" || echo "$2"
}

random_email() {
    ID="$(printf '%x\n' $(python -c 'from time import time; print int(round(time() * 1000))'))"
    echo "$EMAIL_BASE+$ID@govworks.com"
}

get_product() {
    # $1 is the product

    GET_PRODUCT_QUERY="SELECT uuid FROM products WHERE type = 'passport' AND subtype = '$1'"
    RESPONSE="$(sql "$GET_PRODUCT_QUERY")"
    remove_first_line_from_sql_output "$RESPONSE"
}

get_option() {
    # $1 is the domain
    # $2 is the option
    DATA="$(curl --silent --insecure $API_URL/domains/$1/options)"
    OPTION="$2_service"
    UUID="$(node -e "console.log( JSON.parse('$DATA').data.options.find(obj => obj.slug === '$OPTION').uuid );")"
    
    echo "$UUID"
}

get_option_pc() {
    # $1 is the option in slug form. Ex same_day
    get_option 'passportcenter' "$1"
}

get_option_pr() {
    # $1 is the option

    get_option 'passportrenewal' "$1"
}