#! /usr/local/bin/bash

create_options() {
    OPTION_EMAIL=$1

    [[ $FILL == "y" ]] && run core/fillapp "$OPTION_EMAIL" 
    [[ $PROCESS == "y" ]] && run core/process "$OPTION_EMAIL" 
    [[ $REFUND == "y" ]] && run core/refund rar "$OPTION_EMAIL" 
    [[ $INFO == "y" ]] && run core/status "$OPTION_EMAIL"
}

create_auto() {
    EMAIL="$(random_email)"
    run core/createorder 'new-passport' 'standard' ""$EMAIL"" 'passportcenter'
    create_options "$EMAIL"
}

create_custom() {
    EMAIL="$(random_email)"
    run core/createorder "$product" "$shipping" ""$EMAIL"" "$site"
    create_options "$EMAIL"
}

create_e2e() {
    echo "Running E2E for you, sit back and relax"
    echo "At the moment this script only creates an mailaway order in portal"
    cd ~/gw/gov-portal/tests/E2E-Testing && npm i | npm run update | npm run server
    cd ~/gw/gov-portal/tests/E2E-Testing && npm run mailaway
}

create_mailaway() {
    EMAIL="$(random_email)"
    run core/createorder passport-renewal standard "$EMAIL"
    create_options "$EMAIL"
}

create_trial() {
    EMAIL="$(random_email)"
    run core/createtrial new-passport rush "$EMAIL"
    create_options "$EMAIL"
}

custom_options() {
    site_select
    clear
    product_select
    clear
    shipping_select
    clear
    echo "Ok so you want to make a $site.com order for a $product, with $shipping shipping."
}

product_select() {
    echo "Select the product you would like to order"
    product_options=("passport-renewal" "new-passport" "second-passport" "child-passport" "name-change" "lost-passport" "damaged-passport" "stolen-passport") 
    
    select product in "${product_options[@]}"
    do
    case $product in
        "passport-renewal" )
            break;;
        "new-passport" )
            break;;
        "new-passport" )
            break;;
        * )
            echo "That ($product) was not one of the options, try again.";;
    esac
    done
}

prompt_options() {
    echo -n "How many orders would you like to make: "
    read QTY
    clear
    echo -n "Would you like to fill out the user's profile (y/n): "
    read FILL
    clear
    echo -n "After the application is filled out would you like to process the application (y/n): "
    read PROCESS
    clear
    echo -n "Would you like to cancel the order, and create a refund (y/n): "
    read REFUND
    clear
    echo -n "...and finally, do you want the script to print user/order info (y/n): "
    read INFO
    clear
}

script_select() {
    script_options=("auto" "custom" "e2e" "mailaway" "trial")

    select script in "${script_options[@]}"
    do
    case $script in
        "auto" )
            break;;
        "custom" )
            break;;
        "e2e" )
            break;;
        "mailaway" )
            break;;
        "trial" )
            break;;
        * )
            echo "That script you selected ($script) was not one of the options";;
    esac
    done

    clear
    shared/create "$script"
}

shipping_select() {
    echo "Select the shipping speed/service for the order"
    shipping_options=("same_day" "next_day" "priority" "rush" "standard" "smart")

    select shipping in "${shipping_options[@]}"
    do
    case $shipping in
        "same_day" )
            break;;
        "next_day" )
            break;;
        "priority" )
            break;;
        "rush" )
            break;;
        "standard" )
            break;;
        "smart" )
            break;;
        * )
            echo "That ($shipping) was not one of the options";;
    esac
    done
}

site_select() {
    echo "Select the source of the order"
    site_options=("passportcenter" "passportrenewal")

    select site in "${site_options[@]}"
    do
    case $site in
        "passportcenter" )
            break;;
        "passportrenewal" )
            break;;
        * )
            echo "That ($site) was not one of the options, try again";;
    esac
    done
}

case $1 in 
    auto )
        echo "Ok, creating a standard new passport order, should be automanifested."
        prompt_options
        for ((i=0;i<$QTY;i++))
        do
            create_auto
        done
        ;;
    custom )
        echo "Creating a custom order, follow the directions below:"
        custom_options
        echo -n "Is all of the information above correct? (y/n): "
        read ORDER_OK
        if [[ $ORDER_OK == "y" ]];
        then
            clear
            echo -n "Would you like to do some additional tasks, like filling the app? (y/n) "
            read PROMPT
            [ $PROMPT == "y" ] && prompt_options || QTY=1
            for ((i=0;i<$QTY;i++))
            do
                create_custom
            done

        else
            echo "Try again?"
            shared/create
        fi        
        ;;
    e2e )
        echo "Please note, to run this script you have to have e2e installed"
        create_e2e
        ;;
    mailaway )
        echo "Ok, creating a standard mailaway order."
        prompt_options
        for ((i=0;i<$QTY;i++))
        do
            create_mailaway
        done
        ;;
    trial )
        echo "Creating a hot lead / trial order"
        prompt_options
        for ((i=0;i<$QTY;i++))
        do
            create_trial
        done
        ;;
    * ) 
        echo "What type of order would you like to create?"
        echo "Automanifest Order, Custom Order, E2E Order, Mailaway Order, or Trial Order"
        script_select
        ;;
esac



