#! /usr/local/bin/bash

DATE=$(printf '%x\n' $(date +%s))

get_user_info() {
    # Argument 1 is user's email
    GET_PRODUCT_TYPE_QUERY="SELECT users.first_name, users.last_name, products.subtype, orders.order_number, applications.status, applications.progress FROM users JOIN user_orders ON users.id = user_orders.user_id  JOIN orders ON orders.id = user_orders.order_id JOIN travelers ON travelers.order_id = orders.id JOIN applications ON applications.traveler_id = travelers.id JOIN products ON products.id = applications.product_id WHERE users.email = '$1'"
    RESULT="$(sql "$GET_PRODUCT_TYPE_QUERY")"
    USER_INFO=$(remove_first_line_from_sql_output "$RESULT" | awk '{$1=$1};1')
}

create_auto() {
    EMAIL_AUTO=$EMAIL_BASE+PR${DATE}NM@govworks.com
    run core/createorder 'new-passport' 'standard' "$EMAIL_AUTO" 'passportcenter'

    if [ $FILL == "y" ];
    then
        run core/fillapp $EMAIL_AUTO
    fi

    # get_user_info "$EMAIL"
    # USER_PROGRESS="$(cut -d ' ' -f6 <<< $USER_INFO)"
    # && $USER_PROGRESS -eq 100

    if [[ $PROCESS == "y" ]];
    then
        run core/process $EMAIL_AUTO
    else 
        echo "Process App: Application is not ready to be processed"
    fi

    if [ $INFO == "y" ];
    then
        run core/status $EMAIL_AUTO
    fi
}

create_e2e() {
    echo "Running E2E for you, sit back and relax"
    echo "At the moment this script only creates an mailaway order in portal"
    cd ~/gw/gov-portal/tests/E2E-Testing && npm i | npm run update | npm run server
    cd ~/gw/gov-portal/tests/E2E-Testing && npm run mailaway
}

create_mailaway() {
    EMAIL=$EMAIL_BASE+PR${DATE}MA@govworks.com
    run core/createorder 'passport-renewal' 'standard' "$EMAIL"
    
    if [ $FILL == "y" ];
    then
        run core/fillapp $EMAIL
    fi

    get_user_info "$EMAIL"
    USER_PROGRESS="$(cut -d ' ' -f6 <<< $USER_INFO)"

    if [[ $PROCESS == "y" && $USER_PROGRESS -eq 100 ]];
    then
        run core/process $EMAIL
    else 
        echo "Process App: Application is not ready to be processed"
    fi

    if [ $INFO == "y" ];
    then
        run core/status $EMAIL
    fi
}

create_trial() {
    EMAIL=$EMAIL_BASE+PR${DATE}NM@govworks.com
    run core/createtrial new-passport rush $EMAIL

    if [ $FILL == "y" ];
    then
        run core/fillapp $EMAIL
    fi
}

case $1 in 
    mailaway )
        echo "Ok, creating a standard mailaway order."
        echo -n "How many would you like to make: "
        read QTY
        echo -n "Would you like to fill out the user's profile (y/n): "
        read FILL
        echo -n "After the application is filled out would you like to process the application (y/n): "
        read PROCESS
        echo -n "...and finally, do you want the script to print user/order info (y/n): "
        read INFO
        for ((i=0;i<$QTY;i++))
        do
            create_mailaway
        done
        ;;
    auto )
        echo "Ok, creating a standard new passport order."
        echo -n "How many would you like to make: "
        read QTY
        echo -n "Would you like to fill out the user's profile (y/n): "
        read FILL
        echo -n "After the application is filled out would you like to process the application (y/n): "
        read PROCESS
        echo -n "...and finally, do you want the script to print user/order info (y/n): "
        read INFO
        for ((i=0;i<$QTY;i++))
        do
            create_auto
        done
        ;;
    trial )
        echo "Ok, creating a standard new passport order."
        echo -n "How many would you like to make: "
        read QTY
        echo -n "Would you like to fill out the user's profile (y/n): "
        read FILL
        echo -n "After the application is filled out would you like to process the application (y/n): "
        read PROCESS
        echo -n "...and finally, do you want the script to print user/order info (y/n): "
        read INFO
        for ((i=0;i<$QTY;i++))
        do
            create_trial
        done
        ;;
    e2e )
        create_e2e
        ;;
    * ) 
        echo "What type of order would you like to create (auto, e2e, mailaway, trial): "
        read CHOICE
        shared/create "$CHOICE"
        ;;
esac



